<a href="https://colab.research.google.com/github/fabrizionicolay/Big_Data_Colab/blob/main/Practica_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Guía Práctica de NumPy

In [ ]:
import numpy as np

**Creación de Arrays**

In [ ]:
# Creaamos un array unidimensional con 5 elementos enteros de tu elección
vector = np.array([4, 8, 10, 9, 15])
print("Array unidimensional:\n",vector)


Array unidimensional:
 [ 4  8 10  9 15]


In [ ]:
# Creamos una matriz bidimensional de tamaño 3x3 con valores enteros consecutivos
matriz = np.arange(1, 10).reshape(3, 3)
print("Matriz bidimensional:\n",matriz)

Matriz bidimensional:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Creamos una matriz de tamaño 2x4 llena de ceros
matriz_zeros = np.zeros((2, 4), int)
print("Matriz de tamaño 2x4:\n",matriz_zeros)

Matriz de tamaño 2x4:
 [[0 0 0 0]
 [0 0 0 0]]


In [ ]:
# Creamos una matriz de tamaño 3x2 llena de unos
matriz_unos = np.ones((3, 2),int)
print("Matriz de tamaño 3x2:\n",matriz_unos)

Matriz de tamaño 3x2:
 [[1 1]
 [1 1]
 [1 1]]


In [ ]:
# Creamos una matriz de tamaño 4x4 con números enteros aleatorios entre 0 y 10
matriz_random = np.random.randint(0, 11, (4, 4))
print("Matriz de tamaño 4x4:\n",matriz_random)

Matriz de tamaño 4x4:
 [[ 1  8  1  6]
 [ 0  3  0  1]
 [ 8  9  0  2]
 [ 9  6  8 10]]


**Acceso a Elementos**

In [18]:
# Accedemos al tercer elemento del vector
elemento3_vector = vector[2]
print("Tercer elemento del vector:", elemento3_vector)

Tercer elemento del vector: 10


In [20]:
# Accedemos al elemento en la segunda fila y segunda columna de la matriz
elemento_22_matriz = matriz[1, 1]
print("Elemento fila 2 y columna 2:", elemento_22_matriz)

Elemento fila 2 y columna 2: 5


**Propiedades de los Arrays**

In [21]:
# Verificamos la cantidad de dimensiones de la matriz
dimen_matriz = matriz.ndim
print("Cantidad de dimensiones de la matriz:",dimen_matriz)

Cantidad de dimensiones de la matriz: 2


In [22]:
# Obtenemos la forma de la matriz
forma_matriz = matriz.shape
print("Forma de matriz:",forma_matriz)

Forma de matriz: (3, 3)


In [23]:
# Obtenemos el tamaño total de la matriz
tamaño_matriz = matriz.size
print("Tamaño total de la matriz:",tamaño_matriz)

Tamaño total de la matriz: 9


**Operaciones Básicas**

In [26]:
# Suma de dos matrices de tamaño 2x2 con valores aleatorios entre 0 y 10
matriz_a1 = np.random.randint(0, 11, (2, 2))
matriz_a2 = np.random.randint(0, 11, (2, 2))
suma_matrices = matriz_a1 + matriz_a2
print("Primera matriz:\n",matriz_a1, "\n")
print("Segunda matriz:\n",matriz_a2,"\n")
print("Suma de dos matrices 2x2:\n",suma_matrices,"\n")

Primera matriz:
 [[8 9]
 [5 6]] 

Segunda matriz:
 [[10  9]
 [ 0  4]] 

Suma de dos matrices 2x2:
 [[18 18]
 [ 5 10]] 



In [28]:
# Multiplicar dos matrices de tamaño 3x2 y 2x3 respectivamente
matriz_3x2 = np.random.randint(0, 11, (3, 2))
matriz_2x3 = np.random.randint(0, 11, (2, 3))
multiplicacion_matrices = np.dot(matriz_3x2, matriz_2x3)
print("Primera matriz 3x2:\n",matriz_3x2, "\n")
print("Segunda matriz 2x3:\n",matriz_2x3, "\n")
print("Multiplicación de dos matrices:\n",multiplicacion_matrices,"\n")

Primera matriz 3x2:
 [[4 3]
 [2 4]
 [2 4]] 

Segunda matriz 2x3:
 [[1 3 8]
 [3 6 0]] 

Multiplicación de dos matrices:
 [[13 30 32]
 [14 30 16]
 [14 30 16]] 



In [30]:
# Dividir una matriz de tamaño 2x2 por otra matriz de tamaño 2x2
matriz_d1 = np.random.randint(1, 11, (2, 2))
matriz_d2 = np.random.randint(1, 11, (2, 2))
division_elementos = matriz_d1 / matriz_d2
division_inversa = np.dot(matriz_d1, np.linalg.inv(matriz_d2))
print("Primera matriz:\n",matriz_d1, "\n")
print("Segunda matriz:\n",matriz_d2, "\n")
print("Resultado de la división elementos:\n",division_elementos,"\n")
print("Resultado de la división inversa:\n",division_inversa)

Primera matriz:
 [[10  9]
 [ 8  9]] 

Segunda matriz:
 [[ 2  2]
 [10  3]] 

Resultado de la división elementos:
 [[5.  4.5]
 [0.8 3. ]] 

Resultado de la división inversa:
 [[ 4.28571429  0.14285714]
 [ 4.71428571 -0.14285714]]


**Manipulación de Arrays**

In [36]:
# Convertimos el vector en una matriz
matriz_conver = matriz.reshape(9, 1)
print("Matriz:\n",matriz_conver,"\n")

Matriz:
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]] 



In [35]:
# Convertimos la matriz en un vector unidimensional
vector_matriz = matriz.flatten()
print("Matriz unidimensional:\n",vector_matriz)

Matriz unidimensional:
 [1 2 3 4 5 6 7 8 9]


**Operaciones Estadísticas**

In [38]:
# Sumamos todos los elementos de la matriz
suma_elementos_matriz = np.sum(matriz)
print("matriz:\n",matriz,"\n")
print("Suma de elementos de matriz:\n",suma_elementos_matriz,"\n")


matriz:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Suma de elementos de matriz:
 45 



In [57]:
# Calculamos la media de cada fila de la matriz
media_matriz_fila = np.mean(matriz, axis=1)
print("matriz:\n",matriz,"\n")
print("Media de cada fila de matriz:\n",media_matriz_fila)

matriz:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Media de cada fila de matriz:
 [2. 5. 8.]


**Indexación y Rebanado:**

In [40]:
# Obtenemos la primera fila de la matriz
primera_fila = matriz[0]
print("matriz:\n",matriz,"\n")
print("Primera fila de la matriz:\n",primera_fila,"\n")

matriz:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Primera fila de la matriz:
 [1 2 3] 



In [42]:
# Obtenemos las primeras dos columnas de la matriz
primeras_dos_columnas = matriz[:, :2]
print("matriz:\n",matriz,"\n")
print("Primeras columnas de la matriz:\n",primeras_dos_columnas,"\n")

matriz:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Primeras columnas de la matriz:
 [[1 2]
 [4 5]
 [7 8]] 



**Ejercicio Adicional**

In [52]:
# Creamos una matriz de tamaño 4x4 con valores aleatorios
matriz_4x4 = np.random.randint(0, 80, (4, 4))
print("Matriz 4x4:\n",matriz_4x4,"\n")


Matriz 4x4:
 [[25 43 41 62]
 [43 42 66 53]
 [39 30 78 21]
 [31  4 73 35]] 



In [53]:
# Obtenemos el valor máximo y mínimo de la matriz, así como su posición
maximo_valor = np.max(matriz_4x4)
minimo_valor = np.min(matriz_4x4)
posicion_maximo_valor = np.unravel_index(np.argmax(matriz_4x4), matriz_4x4.shape)
posicion_minimo_valor = np.unravel_index(np.argmin(matriz_4x4), matriz_4x4.shape)
print("Valor maximo:",maximo_valor,"\n","Posicion del valor maximo:",posicion_maximo_valor,"\n")
print("Valor minimo:",minimo_valor,"\n","Posicion del valor minimo:",posicion_minimo_valor)

Valor maximo: 78 
 Posicion del valor maximo: (2, 2) 

Valor minimo: 4 
 Posicion del valor minimo: (3, 1)
